---
title: "domestic_airline.Rmd"
author: "SHZ"
#date: "7/25/2019"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    toc_collapse: true
    number_sections: yes
    df_print: paged
    code_folding: "hide"
    theme: sandstone
    highlight: "espresso"
---
<!-- test -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning=F)
library(tidyverse)
```

## Introduction
### downloading dataset

```{r}

fn_data <- "domestic_airline_performance.csv"
fn_notes <- "domestic_airline_performance_notes.txt"

if(!file.exists(fn_data)) {
  url_data <- "https://data.gov.au/data/dataset/29128ebd-dbaa-4ff5-8b86-d9f30de56452/resource/cf663ed1-0c5e-497f-aea9-e74bfda9cf44/download/otp_time_series_web.csv"
  url_notes <- "https://data.gov.au/data/dataset/29128ebd-dbaa-4ff5-8b86-d9f30de56452/resource/69e214b9-b66f-4636-9c84-3efda2d0d8ae/download/otptimeserieswebnotes.txt"

  download.file(url_data, fn_data)
  download.file(url_notes, fn_notes)
}

df <- read_csv(fn_data, quote = "")
df
```

```{r echo = F}
d <- df %>% dim
```

total number of observation `r d[1]` and total number of variables `r d[2]`

```{r echo = F}
df %>%
  group_by(Airline) %>%
  summarise(n = n()) %>%
  arrange(-n)
```

```{r echo = F, eval = T}
df2 <- df %>% filter(Airline != 'All Airlines')
```

## Additional information about the data set 
Not including code here
```{r child = 'domestic_airline_performance_notes.txt'}

```

## Visualisation

Making plots here 
```{r}
df2 <- df %>% filter((Airline == 'Jetstar' | Airline == 'Qantas'),
                     Route != 'All Ports-All Ports')
```

```{r echo = FALSE, fig.align="center", fig.height=4, fig.width=4, fig.cap = "**Figure 1:** *this is a figure*"}
df2 %>%
  group_by(Airline, Year, Departing_Port) %>%
  summarise(n = n()) %>%
  ungroup %>%
    ggplot(aes(Departing_Port, n, color = Airline)) +
    geom_boxplot() +
    theme(axis.text.x=element_text(angle=45, hjust=1))
```

```{r echo = FALSE, fig.height = 4, fig.width = 4}
df2 %>%
  group_by(Airline, Year, Departing_Port) %>%
  summarise(n = n()) %>%
  ungroup %>%
    ggplot(aes(Departing_Port, n, color = Airline)) +
    geom_boxplot() +
    theme(axis.text.x=element_text(angle=45, hjust=1))
```

```{r, fig.width = 14, fig.height = 9}
df2 %>%
  filter(Airline == 'Jetstar' | Airline == 'Qantas') %>%
  select(Airline, Departing_Port, Cancellations, Year) %>%
    ggplot(aes(Departing_Port, Cancellations, color = factor(Year))) +
      geom_boxplot() +
      facet_wrap(~Airline) +
      theme(axis.text.x=element_text(angle= 45, hjust=1))
```

```{r}
print("hello world")
```


```{r prompt=TRUE, comment=""}
sentence <- c('Let', 'the', 'computer', 'do', 'the', 'work')

for(word in sentence){
  print(word)
}
```
<!-- help documentations: ?rmarkdown::render -->
***